"use client";
import Image from "next/image";
import Link from "next/link";
import { Search } from "lucide-react";
import { useMemo, useState } from "react";
import { useAppContext } from "@/hooks/use-app-context";
import { normalize } from "@/lib/search";
import type { Restaurant } from "@/types";
export function RestaurantSelector({ onSelect }: { onSelect: (restaurant: Restaurant) => void }) { const { restaurants,currentUserId }=useAppContext();const [query,setQuery]=useState("");const matches=useMemo(()=>{const normalizedQuery=normalize(query);return restaurants.filter(r=>normalize([r.name,r.neighborhood,...r.cuisine,r.chef].join(" ")).includes(normalizedQuery)&&(r.status!=="rejected")&&(r.status!=="pending_review"||r.submittedBy===currentUserId)).slice(0,7)},[restaurants,query,currentUserId]);const results=query?matches:restaurants.filter(r=>r.status!=="pending_review"&&r.status!=="rejected").slice(0,5);return <section className="mx-auto max-w-xl px-4 py-8 pb-28 lg:py-12"><p className="text-sm font-black text-orange-600">REGISTRAR EXPERIÊNCIA</p><h1 className="mt-1 text-3xl font-black tracking-tight">Onde você foi?</h1><label className="relative mt-6 block"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-stone-400" size={19}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar restaurante" className="w-full rounded-2xl bg-stone-100 py-4 pl-11 pr-4 text-sm outline-none ring-orange-500 focus:ring-2"/></label><p className="mt-6 text-xs font-black uppercase tracking-wide text-stone-500">{query?"Resultados":"Recentes e recomendados"}</p><div className="mt-3 grid gap-2">{results.map(r=><button key={r.id} onClick={()=>onSelect(r)} className="flex items-center gap-3 rounded-2xl bg-white p-3 text-left shadow-sm ring-1 ring-stone-100"><Image src={r.coverPhoto.url} alt="" width={64} height={64} className="h-16 w-16 rounded-xl object-cover"/><span className="min-w-0 flex-1"><b className="block truncate text-sm">{r.name}</b><span className="mt-1 block text-xs text-stone-500">{r.neighborhood} · {r.cuisine[0]}{r.status==="pending_review"&&" · Aguardando validação"}</span></span><span className="rounded-full bg-stone-950 px-2 py-1 text-xs font-black text-white">{r.godinnerRating? r.godinnerRating.toFixed(1):"novo"}</span></button>)}</div>{query&&!results.length&&<div className="mt-8 rounded-3xl border border-dashed border-stone-300 p-6 text-center"><b>Não encontrou esse lugar?</b><Link href={`/restaurant/new?name=${encodeURIComponent(query)}`} className="mt-3 block text-sm font-black text-orange-600">+ Registrar experiência neste lugar</Link></div>}</section>;}
