import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Política de Privacidade | GODINNER",
  description: "Como o GODINNER trata dados pessoais no período Beta.",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="mt-10"><h2 className="text-xl font-black tracking-tight text-stone-900 sm:text-2xl">{title}</h2><div className="mt-3 space-y-4 text-sm leading-7 text-stone-700 sm:text-base">{children}</div></section>;
}

export default function PrivacyPage() {
  return <article className="mx-auto max-w-3xl px-4 py-10 pb-32 sm:px-6 sm:py-14 lg:pb-16">
    <p className="text-sm font-black uppercase tracking-wide text-orange-600">GODINNER</p>
    <h1 className="mt-2 text-3xl font-black tracking-tight text-stone-950 sm:text-4xl">Política de Privacidade do GODINNER</h1>
    <p className="mt-3 text-sm text-stone-500">Última atualização: 1º de setembro de 2026</p>
    <p className="mt-8 text-base leading-7 text-stone-700">Esta Política explica como o GODINNER trata informações pessoais no funcionamento da plataforma social de descoberta e avaliação de restaurantes, bares e outros estabelecimentos gastronômicos. O GODINNER está em Beta e esta Política poderá ser atualizada conforme o produto evoluir.</p>

    <Section title="1. Quem é o GODINNER"><p>O GODINNER é uma plataforma para descobrir lugares, compartilhar experiências e acompanhar avaliações de pessoas. Felipe Borges é o responsável pelo GODINNER e pelo tratamento de dados pessoais no contexto atual do produto em Beta.</p></Section>
    <Section title="2. Dados que podemos tratar"><p>Tratamos dados necessários para criar e manter a conta, o perfil e as funcionalidades da plataforma. Isso pode incluir nome, username, e-mail, foto de perfil, preferências e feedbacks enviados ao GODINNER.</p><p>Também tratamos o conteúdo que a pessoa decide publicar ou interagir, como avaliações, notas, comentários, respostas, fotos, curtidas, follows, menções, listas, lugares salvos ou visitados e gasto por pessoa quando informado.</p><p>Podemos ainda tratar dados técnicos necessários para autenticação, sessão, segurança, diagnóstico de falhas e funcionamento da aplicação.</p></Section>
    <Section title="3. Login com Google"><p>O GODINNER permite entrar usando uma conta Google. Nesse fluxo, utilizamos apenas os escopos básicos de identidade <strong>openid</strong>, <strong>e-mail</strong> e <strong>perfil</strong>, para autenticar a pessoa e criar ou associar sua conta.</p><p>Esses escopos podem fornecer identificador da conta, nome e endereço de e-mail. O GODINNER não solicita acesso ao Gmail, Google Drive, Google Contacts, Google Calendar ou outros serviços Google.</p></Section>
    <Section title="4. Para que usamos os dados"><ul className="list-disc space-y-2 pl-5"><li>criar, autenticar e manter contas e perfis;</li><li>permitir publicação e exibição de experiências e interações sociais;</li><li>operar listas, preferências, notificações e descoberta de restaurantes;</li><li>personalizar a experiência dentro do GODINNER;</li><li>prevenir abuso, fraude e tentativas de comprometer a segurança;</li><li>diagnosticar erros e melhorar o produto durante o Beta.</li></ul></Section>
    <Section title="5. Conteúdo e informações públicas"><p>Algumas informações têm natureza pública na plataforma, como nome público, username, foto de perfil, reviews, notas, fotos publicadas, comentários, respostas, curtidas, follows e listas marcadas como públicas. Esses dados podem ser visualizados por outros usuários conforme a funcionalidade utilizada.</p><p>Listas configuradas como não públicas não são exibidas como conteúdo público para outros usuários.</p></Section>
    <Section title="6. Localização"><p>O GODINNER só usa a localização quando a pessoa autoriza o navegador ou dispositivo para uma ação específica. Ela pode ser usada para mostrar restaurantes próximos, auxiliar buscas, encontrar estabelecimentos e melhorar o contexto de descoberta.</p><p>O GODINNER não realiza rastreamento contínuo de localização por essa funcionalidade e não vende dados de localização.</p></Section>
    <Section title="7. Fornecedores necessários à operação"><p>O GODINNER utiliza fornecedores técnicos para operar o serviço, conforme necessário: Supabase para autenticação, banco de dados e armazenamento; Vercel para hospedagem da aplicação; e serviços Google para autenticação, Google Places e Google Maps quando essas funcionalidades forem utilizadas.</p><p>Esses fornecedores tratam dados conforme as configurações e os serviços necessários à operação. O GODINNER não vende dados pessoais.</p></Section>
    <Section title="8. Sessão e armazenamento necessário"><p>Utilizamos mecanismos de sessão, incluindo cookies de autenticação e armazenamento necessário no navegador, para manter o login, proteger a conta e permitir o funcionamento da aplicação. Não utilizamos uma ferramenta externa de analytics para rastreamento comportamental nesta versão.</p></Section>
    <Section title="9. Retenção e segurança"><p>As informações são mantidas pelo tempo necessário para fornecer o serviço, cumprir obrigações aplicáveis, resolver disputas, prevenir abuso e manter a segurança. Aplicamos medidas técnicas e organizacionais razoáveis para proteger os dados, mas nenhum sistema é totalmente livre de riscos.</p></Section>
    <Section title="10. Seus direitos"><p>Nos termos da LGPD e quando aplicável, você pode solicitar confirmação de tratamento, acesso, correção, informação sobre o tratamento, eliminação, oposição, revogação do consentimento e portabilidade quando cabível.</p><p>O GODINNER ainda não possui um fluxo de autoexclusão de conta. Solicitações relacionadas à exclusão da conta ou aos dados pessoais podem ser enviadas para <a className="font-bold text-orange-600 underline underline-offset-4" href="mailto:suportegodinner@gmail.com">suportegodinner@gmail.com</a>.</p></Section>
    <Section title="11. Menores de idade"><p>O GODINNER ainda não definiu uma política etária específica para o Beta. Uma regra de idade e o tratamento apropriado para menores deverão ser definidos antes de uma divulgação mais ampla da plataforma.</p></Section>
    <Section title="12. Alterações e contato"><p>Esta Política pode ser atualizada para refletir mudanças no GODINNER ou em requisitos aplicáveis. A data da última atualização será sempre indicada no início deste documento.</p><p>Para dúvidas sobre privacidade, utilize <a className="font-bold text-orange-600 underline underline-offset-4" href="mailto:suportegodinner@gmail.com">suportegodinner@gmail.com</a>.</p><p>Consulte também os <Link className="font-bold text-orange-600 underline underline-offset-4" href="/terms">Termos de Uso do GODINNER</Link>.</p></Section>
  </article>;
}
